name: typephp-think

sources:
  - main.php
  - vendor/psr
  - vendor/league/mime-type-detection/src
  - vendor/topthink/framework/src
  - vendor/topthink/think-orm/src
  - vendor/topthink/think-helper/src
  - vendor/topthink/think-container/src
  - vendor/topthink/think-validate/src
  - vendor/topthink/think-trace/src
  - vendor/topthink/think-dumper/src
  - vendor/topthink/think-filesystem/src
  - app
ignore:
  - app/provider.php
  - app/middleware.php
  - app/service.php
  - app/event.php
  - app/ExceptionHandle.php
  - config
  - route
  - extend
  - view
  - vendor/topthink/think-helper/src/helper.php
  - vendor/topthink/framework/src/helper.php
  - vendor/topthink/framework/src/lang/zh-cn.php
  - vendor/topthink/framework/src/think/view/driver/Php.php
  - vendor/topthink/framework/src/think/exception/Handle.php
  - vendor/topthink/think-orm/src/helper.php
  - vendor/topthink/think-validate/src/helper.php
  - vendor/topthink/think-validate/src/Validate.php
  - vendor/topthink/think-trace/src/config.php
  - vendor/topthink/think-trace/src/TraceDebug.php
  - vendor/topthink/think-trace/src/Html.php
  - vendor/topthink/think-trace/src/Console.php
  - vendor/topthink/think-dumper/src/Connection.php
  - vendor/topthink/think-dumper/src/Dumper.php
  - vendor/topthink/think-dumper/src/SourceContextProvider.php
  - vendor/topthink/think-dumper/src/ServerDumper.php
  - vendor/topthink/think-dumper/src/helper.php
  - vendor/topthink/think-filesystem/src/filesystem/Driver.php
  - vendor/topthink/think-filesystem/src/filesystem/driver/Local.php
  - vendor/league/mime-type-detection/src/FinfoMimeTypeDetector.php


output: build/myapp
mode: bin
optimize: 2
job: 8
debug: false
cxx-flags:
  - /bigobj
