
source:
  - app
  - config
  - extend
  - route
  - view
output: build/myapp          # 输出路径，等价于 -o
mode: bin                    # bin / lib / ext
optimize: 2                  # 优化级别，等价于 -O
job: 8                       # 并行任务数
debug: false
