name: typephp-think

sources:
  - main.php
  - vendor/psr
  - vendor/league/mime-type-detection/src
  - vendor/league/flysystem/src
  - vendor/league/flysystem-local
  - vendor/symfony/polyfill-mbstring
  - vendor/symfony/var-dumper
  - vendor/topthink/framework/src
  - vendor/topthink/think-orm/src
  - vendor/topthink/think-helper/src
  - vendor/topthink/think-container/src
  - vendor/topthink/think-validate/src
  - vendor/topthink/think-trace/src
  - vendor/topthink/think-dumper/src
  - vendor/topthink/think-filesystem/src
  - app
ignore:
  - app/provider.php
  - app/middleware.php
  - app/service.php
  - app/event.php
  - config
  - route
  - extend
  - view
  - vendor/topthink/think-helper/src/helper.php
  - vendor/topthink/framework/src/helper.php
  - vendor/topthink/framework/src/lang/zh-cn.php
  - vendor/topthink/framework/src/think/view/driver/Php.php
  - vendor/topthink/think-orm/src/helper.php
  - vendor/topthink/think-validate/src/helper.php
  - vendor/topthink/think-validate/src/Validate.php
  - vendor/topthink/think-trace/src/config.php
  - vendor/topthink/think-dumper/src/helper.php
  - vendor/league/flysystem/src/CalculateChecksumFromStream.php
  - vendor/league/flysystem/src/ProxyArrayAccessToProperties.php
  - vendor/symfony/polyfill-mbstring/bootstrap.php
  - vendor/symfony/polyfill-mbstring/bootstrap72.php
  - vendor/symfony/polyfill-mbstring/bootstrap80.php
  - vendor/symfony/polyfill-mbstring/Resources
  - vendor/symfony/var-dumper/Test/VarDumperTestTrait.php
  - vendor/symfony/var-dumper/Caster/AmqpCaster.php
  - vendor/symfony/var-dumper/Caster/PgSqlCaster.php
  - vendor/symfony/var-dumper/Caster/RedisCaster.php
  - vendor/symfony/var-dumper/Cloner/VarCloner.php
  - vendor/symfony/var-dumper/Command
  - vendor/symfony/var-dumper/Resources/functions/dump.php
  - vendor/topthink/framework/src/think/route/dispatch/Dispatch.php


output: build/myapp
mode: bin
optimize: 2
job: 8
debug: false
cxx-flags:
  - /bigobj
